Use html.escape instead of cgi.escape under Python3
According to Python3's [documentation](https://docs.python.org/3.7/library/cgi.html#cgi.escape)
`cgi.escape` has been deprecated since Python 3.2.
Furthermore it looks like it was removed altogether since Python 3.8.

This PR replaces `cgi.escape` with `html.escape` when the
interpreter is Python3, solving the
`AttributeError: module 'cgi' has no attribute 'escape'` that occurs
when running QUAST with Python 3.8 or newer.